spring.application.name=upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


file.upload-dir=${user.dir}/src/main/resources/static/upload/

password=${pass}