spring.application.name=validatorspringjpa

spring.datasource.url=jdbc:mysql://localhost:3306/pirithika
spring.datasource.username=root
spring.datasource.password=raj123

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
